Bug fix in riv.assembleChannel There was a crash caused (I think) by OutletChanIx not being empty when Closed = True (it should always be empty when closed = true). Crash details pasted below
> Downstream end of outlet channel closed by longshore transport (EndX = -170.325496)
Velocity change in cross-section 57 equals 0.237734 (greater than WarnTol)
Velocity change in cross-section 56 equals 0.206379 (greater than WarnTol)
Velocity change in cross-section 55 equals 0.169533 (greater than WarnTol)
Velocity change in cross-section 54 equals 0.132991 (greater than WarnTol)
Overwashing occuring into closed channel in barrier - redistributing overwash onto barrier top
Time = 2001-07-12 16:01:00, MorDt = 480.0s
Overwashing occuring into closed channel in barrier - redistributing overwash onto barrier top
Overwashing occuring into closed channel in barrier - redistributing overwash onto barrier top
Overwashing occuring into closed channel in barrier - redistributing overwash onto barrier top
Overwashing occuring into closed channel in barrier - redistributing overwash onto barrier top
Overwashing occuring into closed channel in barrier - redistributing overwash onto barrier top
Overwashing occuring into closed channel in barrier - redistributing overwash onto barrier top
Overwashing occuring into closed channel in barrier - redistributing overwash onto barrier top
Overwashing occuring into closed channel in barrier - redistributing overwash onto barrier top
Time = 2001-07-12 17:05:00, MorDt = 480.0s
Overwashing occuring into closed channel in barrier - redistributing overwash onto barrier top
Overwashing occuring into closed channel in barrier - redistributing overwash onto barrier top
Overwashing occuring into closed channel in barrier - redistributing overwash onto barrier top
Overwashing occuring into closed channel in barrier - redistributing overwash onto barrier top
Overwashing occuring into closed channel in barrier - redistributing overwash onto barrier top
Overwashing occuring into closed channel in barrier - redistributing overwash onto barrier top
Overwashing occuring into closed channel in barrier - redistributing overwash onto barrier top
Closed lagoon overtopping at X = -160.000000
Outlet truncation due to breach at X = -160.000000
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\hapuamod\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\ProgramData\Anaconda3\envs\hapuamod\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Projects\HapuaModel\hapuamod\__main__.py", line 45, in <module>
    main(ArgsIn.ModelConfigFile, ArgsIn.Overwrite)
  File "C:\Projects\HapuaModel\hapuamod\core.py", line 172, in main
    ChanFlag, Closed)
  File "C:\Projects\HapuaModel\hapuamod\riv.py", line 589, in storeBedload
    OutletBedload[OutletChanIx] = Bedload[ChanFlag[:-1]==3]
ValueError: shape mismatch: value array of shape (0,) could not be broadcast to indexing result of shape (1,)